# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-06-30 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20220629_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='mobile_phone',
            new_name='phone',
        ),
    ]
