# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-07-01 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='mobile_phone',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='password',
        ),
    ]
