# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-07-01 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20220701_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='mobile_phone',
            field=models.CharField(default=1, max_length=12, verbose_name='电话'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default=1, max_length=32, verbose_name='密码'),
            preserve_default=False,
        ),
    ]
