# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-09-10 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0006_wiki'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='depth',
            field=models.IntegerField(default=1, verbose_name='深度'),
        ),
    ]
