# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-09-30 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0007_wiki_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bucket',
            field=models.CharField(default='xxxx', max_length=128, verbose_name='COS桶'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.CharField(default='eu-frankfurt', max_length=32, verbose_name='COS区域'),
            preserve_default=False,
        ),
    ]
