# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-10-19 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0009_filerepository'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerepository',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='文件路径'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='project_space',
            field=models.PositiveIntegerField(verbose_name='单项目空间/Mb'),
        ),
    ]
