# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-10-19 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0010_auto_20221019_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerepository',
            name='file_size',
            field=models.IntegerField(blank=True, help_text='字节', null=True, verbose_name='文件大小'),
        ),
        migrations.AlterField(
            model_name='project',
            name='use_space',
            field=models.BigIntegerField(default=0, verbose_name='已使用空间'),
        ),
    ]
